services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=alex
      - POSTGRES_DB=nexu_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    external: true
